version: 2.1
jobs:
  build:
    working_directory: ~/androidlibrary
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx4096m
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "androidlibrary_lib/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Download Maven Dependencies
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05
            sudo apt-get update && sudo apt-get install -y maven

      - save_cache:
          paths: 
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "androidlibrary_lib/build.gradle" }}
      # build project
      - run: 
          name: Clean assemble
          command: ./gradlew clean assemble
      - run:
          name: Run Lint Check
          command: ./gradlew lint test
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: androidlibrary_lib/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: androidlibrary_lib/build/test-results
      - run:
          name: Build and package with Maven
          command: mvn -B clean package --file pom.xml
      - run:
          name: Publish artifact to GitHub Packages
          command:
             mvn --batch-mode deploy
            
workflows:
  build:
    jobs:
      - build